import type { Account, Budget, RecurringPayment, Transaction } from "./types";

export const accounts: Account[] = [
  {
    id: "checking",
    name: "Total Checking",
    bank: "Chase",
    type: "Checking",
    balance: 8420.55,
    lastSynced: "2 min ago",
    color: "accent",
  },
  {
    id: "savings",
    name: "Online Savings",
    bank: "Ally",
    type: "Savings",
    balance: 24300,
    lastSynced: "5 min ago",
    color: "info",
  },
  {
    id: "credit",
    name: "Gold Card",
    bank: "Amex",
    type: "Credit",
    balance: -1248.9,
    lastSynced: "Just now",
    color: "warning",
  },
  {
    id: "brokerage",
    name: "Brokerage",
    bank: "Fidelity",
    type: "Investment",
    balance: 42810,
    lastSynced: "1 hr ago",
    color: "brand",
  },
];

export const transactions: Transaction[] = [
  {
    id: "t1",
    merchant: "Whole Foods Market",
    category: "Groceries",
    amount: -127.43,
    date: "Sep 7",
    time: "11:32 AM",
    accountId: "checking",
  },
  {
    id: "t2",
    merchant: "Netflix",
    category: "Subscriptions",
    amount: -15.49,
    date: "Sep 7",
    time: "12:00 AM",
    accountId: "credit",
    recurring: true,
  },
  {
    id: "t3",
    merchant: "Stripe Payout",
    category: "Income",
    amount: 4200,
    date: "Sep 6",
    time: "8:00 AM",
    accountId: "checking",
    note: "Sep freelance",
    recurring: true,
  },
  {
    id: "t4",
    merchant: "Sweetgreen",
    category: "Dining",
    amount: -18.75,
    date: "Sep 6",
    time: "1:15 PM",
    accountId: "credit",
  },
  {
    id: "t5",
    merchant: "Uber",
    category: "Transport",
    amount: -22.1,
    date: "Sep 5",
    time: "7:44 PM",
    accountId: "credit",
  },
  {
    id: "t6",
    merchant: "Spotify",
    category: "Subscriptions",
    amount: -9.99,
    date: "Sep 5",
    time: "12:00 AM",
    accountId: "credit",
    recurring: true,
  },
  {
    id: "t7",
    merchant: "Con Edison",
    category: "Utilities",
    amount: -84.2,
    date: "Sep 4",
    time: "9:00 AM",
    accountId: "checking",
    recurring: true,
  },
];

export const budgets: Budget[] = [
  {
    id: "b1",
    category: "Groceries",
    limit: 500,
    spent: 291.23,
  },
  { id: "b2", category: "Dining", limit: 300, spent: 218.75 },
  {
    id: "b3",
    category: "Transport",
    limit: 150,
    spent: 96.4,
  },
  {
    id: "b4",
    category: "Subscriptions",
    limit: 80,
    spent: 75.47,
  },
  { id: "b5", category: "Health", limit: 200, spent: 24.99 },
];

export const recurringPayments: RecurringPayment[] = [
  {
    id: "r1",
    merchant: "Netflix",
    amount: 15.49,
    cadence: "Monthly",
    next: "Oct 1",
    category: "Subscriptions",
  },
  {
    id: "r2",
    merchant: "Spotify",
    amount: 9.99,
    cadence: "Monthly",
    next: "Oct 5",
    category: "Subscriptions",
  },
  {
    id: "r3",
    merchant: "Con Edison",
    amount: 84.2,
    cadence: "Monthly",
    next: "Oct 4",
    category: "Utilities",
    priceChange: 6.4,
  },
  {
    id: "r4",
    merchant: "Stripe Payout",
    amount: 4200,
    cadence: "Monthly",
    next: "Oct 6",
    category: "Income",
  },
];
